<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE trains [
<!ELEMENT trains (service)>
<!ATTLIST service 
	id CDATA  #REQUIRED
	ligne CDATA  #REQUIRED >
<!ELEMENT service (nom,donnee+)>
	<!ELEMENT nom (#PCDATA)>
	<!ELEMENT donnee (Date,Taux,Nombre)>
		<!ELEMENT Date (#PCDATA)>
		<!ELEMENT Taux (#PCDATA)>
		<!ELEMENT Nombre (#PCDATA)>
]>

<trains >
	<service  id = '1' ligne = 'R'>
		<nom> nom</nom>
		<donnee> 
			<Date> 23-6-10</Date>
			<Taux> 23-6-10</Taux>
			<Nombre> 23-6-10</Nombre>
		</donnee>
	</service>
</trains>
