=== RenonDis/RMDSXMLDTD/ponctualite-mensuelle-transilien.dtd
<!ELEMENT trains (service+)>
<!ELEMENT service (nom_service,ligne+)>
        <!ELEMENT nom_service (#PCDATA)>

        <!ATTLIST ligne
                id CDATA  #REQUIRED
                lettre_ligne CDATA  #REQUIRED >
        <!ELEMENT ligne (nom_ligne,donnee+)>
                <!ELEMENT nom_ligne (#PCDATA)>
                <!ELEMENT donnee (Date,Taux,Nombre)>
                        <!ELEMENT Date (#PCDATA)>
                        <!ELEMENT Taux (#PCDATA)>
                        <!ELEMENT Nombre (#PCDATA)>

=== RenonDis/RMDSXMLDTD/ponctualite-mensuelle-transilien.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet href="style_trains.css" type="text/css"?>
<!DOCTYPE trains SYSTEM "ponctualite-mensuelle-transilien.dtd">
<trains>
  <service>
    <nom_service>RER</nom_service>
    <ligne id="TRA_1" lettre_ligne="A">
      <nom_ligne>RER A</nom_ligne>
      <donnee>
        <Date>Date</Date>
        <Taux>Taux</Taux>
        <Nombre>Nombre</Nombre>
      </donnee>
      <donnee>
        <Date>2013-01</Date>
        <Taux>83.6</Taux>
        <Nombre>5.1</Nombre>
      </donnee>
      <donnee>
        <Date>2013-04</Date>
        <Taux>83.3</Taux>
        <Nombre>5.0</Nombre>
      </donnee>
      <donnee>
        <Date>2013-08</Date>
        <Taux>88.9</Taux>
        <Nombre>8.0</Nombre>
      </donnee>
      <donnee>
        <Date>2014-02</Date>
        <Taux>85.7</Taux>
        <Nombre>6.0</Nombre>
      </donnee>
      <donnee>
        <Date>2015-02</Date>
        <Taux>73.1</Taux>
        <Nombre>2.7</Nombre>
      </donnee>
      <donnee>
        <Date>2015-03</Date>
        <Taux>72.0</Taux>
        <Nombre>2.6</Nombre>
      </donnee>
      <donnee>
        <Date>2015-06</Date>
        <Taux>71.1</Taux>
        <Nombre>2.5</Nombre>
      </donnee>
      <donnee>
        <Date>2013-09</Date>
        <Taux>83.3</Taux>
        <Nombre>5.0</Nombre>
      </donnee>
      <donnee>
        <Date>2013-11</Date>
        <Taux>80.9</Taux>
        <Nombre>4.2</Nombre>
      </donnee>
      <donnee>
        <Date>2014-05</Date>
        <Taux>87.6</Taux>
        <Nombre>7.1</Nombre>
      </donnee>
      <donnee>
        <Date>2014-10</Date>
        <Taux>68.8</Taux>
        <Nombre>2.2</Nombre>
      </donnee>
      <donnee>
        <Date>2014-11</Date>
        <Taux>69.8</Taux>
        <Nombre>2.3</Nombre>
      </donnee>
      <donnee>
        <Date>2015-04</Date>
        <Taux>72.0</Taux>
        <Nombre>2.6</Nombre>
      </donnee>
      <donnee>
        <Date>2015-08</Date>
        <Taux>83.0</Taux>
        <Nombre>4.9</Nombre>
      </donnee>
      <donnee>
        <Date>2013-02</Date>
        <Taux>86.2</Taux>
        <Nombre>6.2</Nombre>
      </donnee>
      <donnee>
        <Date>2013-06</Date>
        <Taux>83.4</Taux>
        <Nombre>5.0</Nombre>
      </donnee>
      <donnee>
        <Date>2013-12</Date>
        <Taux>81.2</Taux>
        <Nombre>4.3</Nombre>
      </donnee>
      <donnee>
        <Date>2014-01</Date>
        <Taux>81.1</Taux>
        <Nombre>4.3</Nombre>
      </donnee>
      <donnee>
        <Date>2014-04</Date>
        <Taux>85.7</Taux>
        <Nombre>6.0</Nombre>
      </donnee>
      <donnee>
        <Date>2014-06</Date>
        <Taux>72.6</Taux>
        <Nombre>2.6</Nombre>
      </donnee>
      <donnee>
        <Date>2014-07</Date>
        <Taux>70.5</Taux>
        <Nombre>2.4</Nombre>
      </donnee>
      <donnee>
        <Date>2014-08</Date>
        <Taux>81.2</Taux>
        <Nombre>4.3</Nombre>
      </donnee>
      <donnee>
        <Date>2013-07</Date>
        <Taux>83.2</Taux>
        <Nombre>5.0</Nombre>
      </donnee>
      <donnee>
        <Date>2014-03</Date>
        <Taux>83.3</Taux>
        <Nombre>5.0</Nombre>
      </donnee>
      <donnee>
        <Date>2015-05</Date>
        <Taux>71.2</Taux>
        <Nombre>2.5</Nombre>
      </donnee>
      <donnee>
        <Date>2013-03</Date>
        <Taux>84.0</Taux>
        <Nombre>5.3</Nombre>
      </donnee>
      <donnee>
        <Date>2013-05</Date>
        <Taux>86.4</Taux>
        <Nombre>6.4</Nombre>
      </donnee>
      <donnee>
        <Date>2013-10</Date>
        <Taux>83.1</Taux>
        <Nombre>4.9</Nombre>
      </donnee>
      <donnee>
        <Date>2014-09</Date>
        <Taux>70.9</Taux>
        <Nombre>2.4</Nombre>
      </donnee>
      <donnee>
        <Date>2014-12</Date>
        <Taux>67.3</Taux>
        <Nombre>2.1</Nombre>
      </donnee>
      <donnee>
        <Date>2015-01</Date>
        <Taux>74.5</Taux>
        <Nombre>2.9</Nombre>
      </donnee>
      <donnee>
        <Date>2015-07</Date>
        <Taux>73.1</Taux>
        <Nombre>2.7</Nombre>
      </donnee>
    </ligne>
    <ligne id="TRA_2" lettre_ligne="B">
      <nom_ligne>RER B</nom_ligne>
      <donnee>
        <Date>Date</Date>
        <Taux>Taux</Taux>
        <Nombre>Nombre</Nombre>
      </donnee>
      <donnee>
        <Date>2013-02</Date>
        <Taux>80.3</Taux>
        <Nombre>4.1</Nombre>
      </donnee>
      <donnee>
        <Date>2013-08</Date>
        <Taux>89.9</Taux>
        <Nombre>8.9</Nombre>
      </donnee>
      <donnee>
        <Date>2013-09</Date>
        <Taux>86.6</Taux>
        <Nombre>6.5</Nombre>
      </donnee>
      <donnee>
        <Date>2014-03</Date>
        <Taux>87.9</Taux>
        <Nombre>7.3</Nombre>
      </donnee>
      <donnee>
        <Date>2014-07</Date>
        <Taux>86.9</Taux>
        <Nombre>6.6</Nombre>
      </donnee>
      <donnee>
        <Date>2015-04</Date>
        <Taux>86.2</Taux>
        <Nombre>6.2</Nombre>
      </donnee>
      <donnee>
        <Date>2015-07</Date>
        <Taux>90.9</Taux>
        <Nombre>10.0</Nombre>
      </donnee>
      <donnee>
        <Date>2013-11</Date>
        <Taux>77.9</Taux>
        <Nombre>3.5</Nombre>
      </donnee>
      <donnee>
        <Date>2014-04</Date>
        <Taux>88.5</Taux>
        <Nombre>7.7</Nombre>
      </donnee>
      <donnee>
        <Date>2014-06</Date>
        <Taux>NaN</Taux>
        <Nombre>0.0</Nombre>
      </donnee>
      <donnee>
        <Date>2014-09</Date>
        <Taux>87.4</Taux>
        <Nombre>6.9</Nombre>
      </donnee>
      <donnee>
        <Date>2015-02</Date>
        <Taux>85.4</Taux>
        <Nombre>5.8</Nombre>
      </donnee>
      <donnee>
        <Date>2015-05</Date>
        <Taux>87.0</Taux>
        <Nombre>6.7</Nombre>
      </donnee>
      <donnee>
        <Date>2015-06</Date>
        <Taux>85.0</Taux>
        <Nombre>5.7</Nombre>
      </donnee>
      <donnee>
        <Date>2013-07</Date>
        <Taux>84.1</Taux>
        <Nombre>5.3</Nombre>
      </donnee>
      <donnee>
        <Date>2014-01</Date>
        <Taux>81.3</Taux>
        <Nombre>4.3</Nombre>
      </donnee>
      <donnee>
        <Date>2014-02</Date>
        <Taux>88.9</Taux>
        <Nombre>8.0</Nombre>
      </donnee>
      <donnee>
        <Date>2014-05</Date>
        <Taux>89.4</Taux>
        <Nombre>8.4</Nombre>
      </donnee>
      <donnee>
        <Date>2014-08</Date>
        <Taux>90.7</Taux>
        <Nombre>9.8</Nombre>
      </donnee>
      <donnee>
        <Date>2014-10</Date>
        <Taux>85.5</Taux>
        <Nombre>5.9</Nombre>
      </donnee>
      <donnee>
        <Date>2014-11</Date>
        <Taux>86.1</Taux>
        <Nombre>6.2</Nombre>
      </donnee>
      <donnee>
        <Date>2014-12</Date>
        <Taux>84.6</Taux>
        <Nombre>5.5</Nombre>
      </donnee>
      <donnee>
        <Date>2015-01</Date>
        <Taux>88.5</Taux>
        <Nombre>7.7</Nombre>
      </donnee>
      <donnee>
        <Date>2015-03</Date>
        <Taux>89.9</Taux>
        <Nombre>8.9</Nombre>
      </donnee>
      <donnee>
        <Date>2015-08</Date>
        <Taux>92.9</Taux>
        <Nombre>13.1</Nombre>
      </donnee>
      <donnee>
        <Date>2013-03</Date>
        <Taux>82.7</Taux>
        <Nombre>4.8</Nombre>
      </donnee>
      <donnee>
        <Date>2013-04</Date>
        <Taux>86.4</Taux>
        <Nombre>6.4</Nombre>
      </donnee>
      <donnee>
        <Date>2013-10</Date>
        <Taux>80.7</Taux>
        <Nombre>4.2</Nombre>
      </donnee>
      <donnee>
        <Date>2013-01</Date>
        <Taux>80.1</Taux>
        <Nombre>4.0</Nombre>
      </donnee>
      <donnee>
        <Date>2013-05</Date>
        <Taux>84.0</Taux>
        <Nombre>5.3</Nombre>
      </donnee>
      <donnee>
        <Date>2013-06</Date>
        <Taux>82.2</Taux>
        <Nombre>4.6</Nombre>
      </donnee>
      <donnee>
        <Date>2013-12</Date>
        <Taux>82.4</Taux>
        <Nombre>4.7</Nombre>
      </donnee>
    </ligne>
    <ligne id="TRA_4" lettre_ligne="D">
      <nom_ligne>RER D</nom_ligne>
      <donnee>
        <Date>Date</Date>
        <Taux>Taux</Taux>
        <Nombre>Nombre</Nombre>
      </donnee>
      <donnee>
        <Date>2013-03</Date>
        <Taux>80.0</Taux>
        <Nombre>4.0</Nombre>
      </donnee>
      <donnee>
        <Date>2014-01</Date>
        <Taux>86.0</Taux>
        <Nombre>6.1</Nombre>
      </donnee>
      <donnee>
        <Date>2014-02</Date>
        <Taux>88.2</Taux>
        <Nombre>7.5</Nombre>
      </donnee>
      <donnee>
        <Date>2014-07</Date>
        <Taux>86.6</Taux>
        <Nombre>6.5</Nombre>
      </donnee>
      <donnee>
        <Date>2014-10</Date>
        <Taux>81.4</Taux>
        <Nombre>4.4</Nombre>
      </donnee>
      <donnee>
        <Date>2015-01</Date>
        <Taux>86.6</Taux>
        <Nombre>6.4</Nombre>
      </donnee>
      <donnee>
        <Date>2015-07</Date>
        <Taux>87.7</Taux>
        <Nombre>7.1</Nombre>
      </donnee>
      <donnee>
        <Date>2013-01</Date>
        <Taux>77.6</Taux>
        <Nombre>3.5</Nombre>
      </donnee>
      <donnee>
        <Date>2013-05</Date>
        <Taux>87.1</Taux>
        <Nombre>6.8</Nombre>
      </donnee>
      <donnee>
        <Date>2013-09</Date>
        <Taux>83.1</Taux>
        <Nombre>4.9</Nombre>
      </donnee>
      <donnee>
        <Date>2015-05</Date>
        <Taux>86.4</Taux>
        <Nombre>6.3</Nombre>
      </donnee>
      <donnee>
        <Date>2013-08</Date>
        <Taux>90.4</Taux>
        <Nombre>9.4</Nombre>
      </donnee>
      <donnee>
        <Date>2013-10</Date>
        <Taux>79.6</Taux>
        <Nombre>3.9</Nombre>
      </donnee>
      <donnee>
        <Date>2014-05</Date>
        <Taux>85.9</Taux>
        <Nombre>6.1</Nombre>
      </donnee>
      <donnee>
        <Date>2014-08</Date>
        <Taux>92.0</Taux>
        <Nombre>11.5</Nombre>
      </donnee>
      <donnee>
        <Date>2014-09</Date>
        <Taux>87.0</Taux>
